spring.application.name=13_department-service_Microservices

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/department_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

employee.service.url=http://localhost:8081